RickLeinecker/SeeShells

WPF/SeeShells/SeeShells/SeeShells.csproj, WPF/SeeShells/SeeShells/ShellParser/OnlineRegistryReader.cs, WPF/SeeShells/SeeShells/ShellParser/RegistryKeyWrapper.cs, WPF/SeeShells/SeeShellsTests/SeeShellsTests.csproj, WPF/SeeShells/SeeShellsTests/ShellParser/OnlineRegistryReaderTests.cs
enables dynamic scanning of a live-system registry given paths under HKEY_CURRENT_USER and HKEY_USERS
fixes #27
=> Add Online Registry Reader

WPF/SeeShells/SeeShells/SeeShells.csproj, WPF/SeeShells/SeeShells/ShellParser/ShellItems/IShellItem.cs
Skeleton creation for parallel work for issue #51
=> Adds IShellItem Interface Skeleton

WPF/SeeShells/SeeShells/ShellParser/ShellItems/IShellItem.cs
=> Add documentation to the IShellItem Interfaces contents

WPF/SeeShells/SeeShells/SeeShells.csproj, WPF/SeeShells/SeeShells/UI/IEvent.cs
This interface will serve as the basis for elements that appear on the graphical timeline, providing a starting point for issues #35 and #36
=> Adds IEvent Interface

WPF/SeeShells/SeeShells/IO/CsvIO.cs, WPF/SeeShells/SeeShells/SeeShells.csproj, WPF/SeeShells/SeeShellsTests/IO/CsvIOTests.cs, WPF/SeeShells/SeeShellsTests/SeeShellsTests.csproj
This is my idea of static classes to be used for CSV and HTML IO
=> A skeleton of CSV IO (HTML IO should be similar)

WPF/SeeShells/SeeShells/SeeShells.csproj, WPF/SeeShells/SeeShells/UI/FilterEventUtils.cs, WPF/SeeShells/SeeShells/UI/IEvent.cs, WPF/SeeShells/SeeShellsTests/SeeShellsTests.csproj, WPF/SeeShells/SeeShellsTests/UI/FilterEventUtilsTests.cs, WPF/SeeShells/SeeShellsTests/UI/Mocks/MockEvent.cs, WPF/SeeShells/SeeShellsTests/UI/Mocks/MockShellItem.cs
Adds Filtering functions on IEvent Properties 
Add Relevant test cases
Progresses #36
=> Adds IEvent Filter Utilities

api/JSONhelper.js, api/databaseconnection.js, api/index.js
I also slightly modified getGUID
=> Added Get OS&Registry locations API endpoint

.github/workflows/WPFUnitTests.yml, WPF/SeeShells/SeeShellsTests/ShellParser/OnlineRegistryReaderTests.cs, WPF/SeeShells/SeeShellsTests/ShellParser/ShellBagParserTests.cs
Adds Github Action to preform unit tests that dont need a online registry.
When merged, Github will preform unit test checking on any new PR that gets generated
=> Adds CI for WPF Unit Tests

api/JSONhelper.js, api/databaseconnection.js, api/index.js
These 2 endpoints let us add new OS versions. The regular add OS endpoint lets us add a new version that uses the same registry key locations as a previous version (#103 ). The add OS with file locations endpoint lets us add a new version that has different registry key locations (#116 ).
=> Add OS API Endpoints

.github/workflows/ApiBuildTest.yml, .github/workflows/WPFUnitTests.yml, .github/workflows/WebsiteBuildTest.yml, api/package.json, docs/package.json
- Auto Adds Label marking to PR's
- Corrects License in package.jsons
- Update Website package license
- Run WPF CI on WPF edits only
- Add CI to API and Website
=> Update CI and edit licenses

WPF/SeeShells/SeeShells/UI/EventFilters/INodeFilter.cs, WPF/SeeShells/SeeShells/UI/Node/NodeCollection.cs, WPF/SeeShells/SeeShells/UI/Pages/TimelinePage.xaml, WPF/SeeShells/SeeShells/UI/Pages/TimelinePage.xaml.cs
- Redesigns Timeline page Filter section to better reflect existing EventFilters
- Adds default list for NodeCollection to Null Point Exceptions
- Moves INodeFilter to EventFilters
Resolves #107 
New Timeline Screen:
=> Adds new event filters GUI

WPF/SeeShells/SeeShells/UI/Pages/Home.xaml, WPF/SeeShells/SeeShells/UI/Pages/Home.xaml.cs, WPF/SeeShells/SeeShells/UI/Templates/CheckBoxWithLabel.xaml, WPF/SeeShells/SeeShells/UI/Templates/CheckBoxWithLabel.xaml.cs, WPF/SeeShells/SeeShells/UI/ViewModels/FileLocations.cs
=> Browse button for offline hive lets user select .reg file and user can select OS Version

WPF/SeeShells/SeeShells/UI/Pages/Home.xaml.cs
- change debug MessageBox to logged message
- refactored error messageboxes to common function
- fixes null check on OSVersion
=> Update Parse Button to work with Timeline

WPF/SeeShells/SeeShells/UI/Pages/TimelinePage.xaml.cs
Improves the speed by not rebuilding the timeline from scratch every time a new scaling factor is given.
The scaling slider control is smooth like butter up to 3000 events. I've also tested and it shows acceptable speed up to 10,000 events with minimal lag.
=> Improves rescaling runtime speed.

WPF/SeeShells/SeeShells/IO/HtmlIO.cs, WPF/SeeShells/SeeShells/SeeShells.csproj, WPF/SeeShells/SeeShells/UI/Pages/TimelinePage.xaml, WPF/SeeShells/SeeShells/UI/Pages/TimelinePage.xaml.cs, WPF/SeeShells/SeeShellsTests/IO/HtmlIOTests.cs, WPF/SeeShells/SeeShellsTests/SeeShellsTests.csproj
This creates the HTML File of the filtered timeline. This also includes the Unit Test for it. Resolves #39
=> HTML Output

WPF/SeeShells/SeeShells/UI/EventFilters/EventNameFilter.cs, WPF/SeeShells/SeeShells/UI/Pages/TimelinePage.xaml, WPF/SeeShells/SeeShells/UI/Pages/TimelinePage.xaml.cs
- Adds the ability to multiselect eventTypes via the UI
- Fixes bug in event type where options would be duplicated upon opening
- fixes duplicate "hours" in timeline scaling combobox
Resolves #154
=> Adds multiselect to event type filter and fixes combobox duplications

WPF/SeeShells/SeeShells/UI/Pages/Home.xaml.cs
- removes expired TODO and FIXME in home view page
This issue is a subset of #137 for being able to do parsing offline
Resolves #140
=> #140 Removes requirement of a script.json to parse

WPF/SeeShells/SeeShells/UI/Pages/TimelinePage.xaml.cs
Connects the CSV function to UI. Resolve #127
=> Connect the CsvIO to UI checkbox

WPF/SeeShells/SeeShells/UI/Pages/Home.xaml, WPF/SeeShells/SeeShells/UI/Pages/Home.xaml.cs
=> Blocked button operations while parsing is in progress.

WPF/SeeShells/SeeShells/SeeShells.csproj, WPF/SeeShells/SeeShells/UI/EventFilters/EventUserFilter.cs, WPF/SeeShells/SeeShells/UI/Pages/TimelinePage.xaml, WPF/SeeShells/SeeShells/UI/Pages/TimelinePage.xaml.cs, WPF/SeeShells/SeeShellsTests/UI/Mocks/MockShellItem.cs, WPF/SeeShells/SeeShellsTests/UI/NodeFilterTests.cs
- Adds Unit test for new EventUserFilter
Progresses #164
=> Adds UI Filter for Users

api/databaseconnection.js, api/index.js
Resolves #180 
Resolves #181 
Also made session timeout shorter while I was at it.
=> Get and change help info API endpoints created

WPF/SeeShells/SeeShells/App.xaml, WPF/SeeShells/SeeShells/App.xaml.cs, WPF/SeeShells/SeeShells/UI/Pages/HelpPage.xaml, WPF/SeeShells/SeeShells/UI/Pages/Home.xaml, WPF/SeeShells/SeeShells/UI/Pages/TimelinePage.xaml
- Adds "View" menu with two page views
- Adds About Me Toolbar menu
Resolves #187
=> Adds Toolbar to Application

WPF/SeeShells/SeeShells/UI/EventFilters/AnyStringFilter.cs, WPF/SeeShells/SeeShells/UI/EventFilters/DateRangeFilter.cs, WPF/SeeShells/SeeShells/UI/EventFilters/EventNameFilter.cs, WPF/SeeShells/SeeShells/UI/EventFilters/EventParentFilter.cs, WPF/SeeShells/SeeShells/UI/EventFilters/EventTypeFilter.cs, WPF/SeeShells/SeeShells/UI/EventFilters/EventUserFilter.cs, WPF/SeeShells/SeeShells/UI/Node/Node.cs, WPF/SeeShells/SeeShells/UI/Node/NodeCollection.cs, WPF/SeeShells/SeeShells/UI/Node/NodeParser.cs, WPF/SeeShells/SeeShells/UI/Pages/TimelinePage.xaml.cs, WPF/SeeShells/SeeShellsTests/IO/HtmlIOTests.cs, WPF/SeeShells/SeeShellsTests/SeeShellsTests.csproj, WPF/SeeShells/SeeShellsTests/UI/Mocks/MockNode.cs, WPF/SeeShells/SeeShellsTests/UI/Mocks/MockNodeFilter.cs, WPF/SeeShells/SeeShellsTests/UI/NodeCollectionTest.cs, WPF/SeeShells/SeeShellsTests/UI/NodeFilterTests.cs, WPF/SeeShells/SeeShellsTests/packages.config
This has the same effect as the old pull request to resolve clickable objects, but without an extra class. Resolve #87
=> Node fixes

WPF/SeeShells/SeeShells/UI/Node/NodeParser.cs, WPF/SeeShells/SeeShells/UI/Node/StackedNodes.cs, WPF/SeeShells/SeeShells/UI/Pages/TimelinePage.xaml, WPF/SeeShells/SeeShells/UI/Pages/TimelinePage.xaml.cs
1. Adds ticks to graph out each second of the timeline. (the ticks are placed in a TimelinePanel which handles their spacing)
2. Adds separation lines to designate the end of one timeline and start of another.
3. Adds a timeline bar to represent the continuous timeline.
4. Adds lines to connect each node to the timeline bar in order to pinpoint their location in relation to the ticks on the bar.
Note:
Due to a significant amount of objects being added to the UI, the program has a slight slowdown. It takes about extra 3 to 4 seconds to parse and 0 to 4 seconds to redraw after filters are applied depending on how large the filtered amount of events is. However, I am running it on pretty fast hardware, thus the slowdown might be more severe on lower end machines. This will be something to …
=> Pretty timeline

WPF/SeeShells/SeeShells/UI/Node/Node.cs, WPF/SeeShells/SeeShells/UI/Node/StackedNodes.cs, WPF/SeeShells/SeeShells/UI/Pages/TimelinePage.xaml.cs, WPF/SeeShells/SeeShells/UI/Templates/NodeStyle.xaml
The Node and StackedNode were changed to toggle buttons, a new style was added and the functionality works. Resolves #245
=> Change color of textblock when node is hovered over

WPF/SeeShells/SeeShells/UI/Pages/TimelinePage.xaml, WPF/SeeShells/SeeShells/UI/Pages/TimelinePage.xaml.cs
Adds a clear button to each individual filter.
I did not add a clear all filter as it seems unnecessary.
Resolves #203
=> Adds buttons to clear each individual filter

WPF/SeeShells/SeeShells/UI/Pages/TimelinePage.xaml
closes issue #269 
it was a quick fix so I thought I would just take care of it.
=> fixes cutoff issue

WPF/SeeShells/SeeShells/App.xaml, WPF/SeeShells/SeeShells/SeeShells.csproj, WPF/SeeShells/SeeShells/UI/Node/InfoBlock.cs, WPF/SeeShells/SeeShells/UI/Node/NodeParser.cs, WPF/SeeShells/SeeShells/UI/Pages/TimelinePage.xaml.cs, WPF/SeeShells/SeeShells/UI/Windows/EventInformationWindow.xaml, WPF/SeeShells/SeeShells/UI/Windows/EventInformationWindow.xaml.cs
Resolves #246 
When users click on an event, a pop up window with the information appears:
Also removed blockList variable in TimelinePage which didn't seem to be doing anything. (Tell me if it is)
=> Event click window

WPF/SeeShells/SeeShells/App.xaml.cs
=> Should write any error messages that crash the application.

WPF/SeeShells/SeeShells/UI/EventFilters/AnyStringFilter.cs
- Fixes bug where regex would crash on matching invalid regex
- Fixes bug where regex would remove all nodes after an exception
=> Fixes outdated Regex matching filter

WPF/SeeShells/Help.md
- Adds help content about the Timeline page
- Adds help content about the Toolbar and its controls
Resolves #208 and Resolves #40
=> Updates Help with Timeline and Toolbar documentation

WPF/SeeShells/SeeShells/UI/Pages/Home.xaml, WPF/SeeShells/SeeShells/UI/Pages/Home.xaml.cs
Resolves #299 .  This has now frozen all the buttons in the UI during parsing.
=> Freeze UI when parsing

WPF/SeeShells/SeeShells/ShellParser/Registry/RegistryKeyWrapper.cs
Fixes the RegistryPath value for offline events.
=> Fixes the RegistryPath value for events.

WPF/SeeShells/SeeShells/UI/Node/NodeParser.cs, WPF/SeeShells/SeeShells/UI/Pages/TimelinePage.xaml.cs
This has the option to open a new window with event data or filter with that certain event. Resolves #303. Resolves #304
=> Adds a context menu on right click

WPF/SeeShells/SeeShells/Constants.cs, WPF/SeeShells/SeeShells/IO/CsvParsedShellItem.cs, WPF/SeeShells/SeeShells/SeeShells.csproj, WPF/SeeShells/SeeShells/ShellParser/Registry/RegistryShellItemDecorator.cs, WPF/SeeShells/SeeShells/ShellParser/Scripting/LuaShellItem.cs, WPF/SeeShells/SeeShells/ShellParser/ShellItems/ExtensionBlocks/ExtensionBlock.cs, WPF/SeeShells/SeeShells/ShellParser/ShellItems/ExtensionBlocks/ExtensionBlockBEEF0004.cs, WPF/SeeShells/SeeShells/ShellParser/ShellItems/SHITEM_UNKNOWNENTRY2.cs, WPF/SeeShells/SeeShells/ShellParser/ShellItems/ShellItem.cs, WPF/SeeShells/SeeShells/ShellParser/ShellItems/ShellItem0x00.cs, WPF/SeeShells/SeeShells/ShellParser/ShellItems/ShellItem0x1F.cs, WPF/SeeShells/SeeShells/ShellParser/ShellItems/ShellItem0x30.cs, WPF/SeeShells/SeeShells/ShellParser/ShellItems/ShellItem0x40.cs, WPF/SeeShells/SeeShells/ShellParser/ShellItems/ShellItem0x4D.cs, WPF/SeeShells/SeeShells/ShellParser/ShellItems/ShellItem0x61.cs, WPF/SeeShells/SeeShells/ShellParser/ShellItems/ShellItem0x71.cs, WPF/SeeShells/SeeShells/ShellParser/ShellItems/ShellItem0x74.cs
resolves issue #177
I created a constants class and moved known key names embedded in shellitem and supporting classes there and refactored.
=> Refactor Property names to centralized location

WPF/SeeShells/SeeShells/UI/Pages/Home.xaml.cs
=> Adds Save Dialog to Update Buttons

WPF/SeeShells/Help.md, WPF/SeeShells/SeeShells/ShellParser/Registry/OnlineRegistryReader.cs, WPF/SeeShells/SeeShells/ShellParser/Registry/RegistryKeyWrapper.cs, WPF/SeeShells/SeeShells/UI/Pages/Home.xaml, WPF/SeeShells/SeeShells/UI/Pages/Home.xaml.cs, WPF/SeeShells/SeeShells/UI/Pages/TimelinePage.xaml.cs
- Added registry traversal for logged off users
- Added UI option to toggle Multi-User online parsing
- Fixed bug in Online Username resolution where the _classes SID wouldnt resolve (postmortem  #192)
- Fixed bug in Timeline UI where Filter dropdowns wouldnt update on a second parsing attempt
- Removed TODOs regarding username support in RegistryKeyWrapper
Resolves #278
=> Fixes Online Multi-User Support

.gitattributes, SeeShells How To.mp4
=> Add How To Video
