WPF/SeeShells/SeeShells/ShellParser/OnlineRegistryReader.cs
WPF/SeeShells/SeeShellsTests/ShellParser/ShellParserMocks/MockConfigParser.cs

Sets up future code to be able to divide shellbags by user SID
Updates test for onlineRegistryReader to read both BagsMRU and Bags in all known locations.

Remove functionality of looking in CurrentUser hive.

---

WPF/SeeShells/SeeShells/IO/Networking/API.cs
WPF/SeeShells/SeeShells/IO/Networking/APIException.cs
WPF/SeeShells/SeeShells/IO/Networking/JSON/APIError.cs
WPF/SeeShells/SeeShells/IO/Networking/JSON/GUIDPair.cs
WPF/SeeShells/SeeShells/IO/Networking/JSON/RegistryLocations.cs
WPF/SeeShells/SeeShells/SeeShells.csproj
WPF/SeeShells/SeeShells/packages.config
WPF/SeeShells/SeeShellsTests/IO/Networking/APITests.cs
WPF/SeeShells/SeeShellsTests/IO/Networking/JSONTests.cs
WPF/SeeShells/SeeShellsTests/SeeShellsTests.csproj
WPF/SeeShells/SeeShellsTests/TestResource/sampleAPIError.json
WPF/SeeShells/SeeShellsTests/TestResource/sampleGUIDs.json
WPF/SeeShells/SeeShellsTests/TestResource/sampleGUIDsResponse.json
WPF/SeeShells/SeeShellsTests/TestResource/sampleOSRegistryLocations.json
WPF/SeeShells/SeeShellsTests/TestResource/sampleOSRegistryLocationsResponse.json
WPF/SeeShells/SeeShellsTests/packages.config
docs/apiEndpoint.txt

- Adds networking dependencies for future api calls
- Adds special endpoint to website for the WPF application
- Adds GUIDs and OsRegistryLocation API Calls and file writing
- Adds json2poco classes
- Adds respective unit tests for all functionality
Resolves #108 & #110

Add functionality for 2 API calls to WPF

---

WPF/SeeShells/SeeShells/App.xaml.cs
WPF/SeeShells/SeeShells/SeeShells.csproj
WPF/SeeShells/SeeShells/UI/Node/Node.cs
WPF/SeeShells/SeeShells/UI/Node/NodeCollection.cs
WPF/SeeShells/SeeShells/UI/Node/NodeParser.cs
WPF/SeeShells/SeeShellsTests/SeeShellsTests.csproj
WPF/SeeShells/SeeShellsTests/UI/NodeCollectionTest.cs

Introduces the following classes:
Node -> Formerly called Pretty Object, containing graphical objects to be displayed on a timeline.
NodeCollection -> Formerly called PrettyObjectCollection, used to store a list of nodes and be globally accessible from the App class
NodeParser -> Used to populate the the list of nodes in the NodeCollection from a list of Events

Node, NodeCollection and NodeParser Skeleton

---

WPF/SeeShells/SeeShells/App.xaml.cs
WPF/SeeShells/SeeShells/ShellParser/ConfigParser.cs
WPF/SeeShells/SeeShells/ShellParser/IConfigParser.cs
WPF/SeeShells/SeeShells/ShellParser/OfflineRegistryReader.cs
WPF/SeeShells/SeeShells/ShellParser/OnlineRegistryReader.cs
WPF/SeeShells/SeeShells/ShellParser/ShellBagParser.cs
WPF/SeeShells/SeeShells/UI/Pages/Home.xaml.cs
WPF/SeeShells/SeeShellsTests/ShellParser/ShellBagParserTests.cs
WPF/SeeShells/SeeShellsTests/ShellParser/ShellParserMocks/MockConfigParser.cs
WPF/SeeShells/SeeShellsTests/ShellParser/ShellParserMocks/OfflineMockConfigParser.cs

- Makes ShellBagParser a static class and method
- Creates a global ShellItem list for the purposes of exporting
- Not fully functional until Timeline & EventParser can be applied
- Implements ConfigParser and Refactors IConfigParser
- Creates Debug MessageBox for output of parse button
Questionably resolves #129 
**Not to be merged until #134 is merged**

Enables Parse Button

---

WPF/SeeShells/SeeShells/UI/Pages/TimelinePage.xaml
WPF/SeeShells/SeeShells/UI/Pages/TimelinePage.xaml.cs

Introduces a slider control which can be used to control the spacing between events on the timeline.
It also adds a text and combo box for fine tuning the slider's location.
Resolves #89

Timeline Spacing Slider Control

---

WPF/SeeShells/SeeShells/UI/Pages/Home.xaml
WPF/SeeShells/SeeShells/UI/Pages/Home.xaml.cs
WPF/SeeShells/SeeShells/UI/ViewModels/FileLocations.cs

Resolves #138 
So, there is a checkbox in the file explorer when you allow multiple files to be selected; I don't think we need to add a button to add more files since this seems pretty intuitive to me.
I modified the rest of the code to handle the string array the file dialog returns now instead of the single string.

Multiple offline files can be chosen.

---

WPF/SeeShells/SeeShells/UI/EventFilters/AnyStringFilter.cs
WPF/SeeShells/SeeShells/UI/EventFilters/DateRangeFilter.cs
WPF/SeeShells/SeeShells/UI/EventFilters/EventNameFilter.cs
WPF/SeeShells/SeeShells/UI/EventFilters/EventParentFilter.cs
WPF/SeeShells/SeeShells/UI/EventFilters/EventTypeFilter.cs
WPF/SeeShells/SeeShells/UI/Node/NodeCollection.cs
WPF/SeeShells/SeeShellsTests/UI/NodeFilterTests.cs

- fixed error where datetime and event type filters would destroy nodes instead of hiding
- modified unit tests to check for consistent number of nodes during filtering
- Added "blank" filter handling for event name and event type
- added functionality to restore nodes previously hidden when removing filters
Resolves #155

#155 fixes various filtering errors

---

api/databaseconnection.js
api/index.js
api/package-lock.json
api/package.json

Resolves #81 
Edited:
Resolves #82 
The add scripts endpoint will only accept base 64 encoded strings. When a user inputs a script on the website, the script will need to be encoded before being sent.
The get scripts endpoint will return these encoded strings. When the website receives these, it will need to decode them before displaying them to the user.

Add script API endpoint adds a script to the database

---

.gitignore
WPF/SeeShells/.gitignore
WPF/SeeShells/SeeShells/IO/Networking/API.cs
WPF/SeeShells/SeeShells/NLog.config
WPF/SeeShells/SeeShells/UI/MainWindow.xaml.cs

Resolves #168 
If too much information is being printed, you can modify minlevel in the logger rules.

NLog Fixed

---

WPF/SeeShells/SeeShells/UI/EventParser.cs
WPF/SeeShells/SeeShellsTests/UI/EventParserTest.cs

- fixes unit test for EventParser to run with MSTest
Resolves #170

Order events by ascending eventTimes during list creation

---

WPF/SeeShells/SeeShells/App.xaml.cs
WPF/SeeShells/SeeShells/IO/Networking/API.cs
WPF/SeeShells/SeeShells/IO/Networking/JSON/ScriptPair.cs
WPF/SeeShells/SeeShells/SeeShells.csproj
WPF/SeeShells/SeeShells/ShellParser/ConfigParser.cs
WPF/SeeShells/SeeShells/ShellParser/Scripting/LuaShellItem.cs
WPF/SeeShells/SeeShells/ShellParser/Scripting/ScriptHandler.cs
WPF/SeeShells/SeeShells/ShellParser/ShellItems/ShellItemList.cs
WPF/SeeShells/SeeShells/UI/Pages/Home.xaml.cs

Resolves #147 
The code added in the IO Networking folder covers this part. The API endpoint is hit, and the JSON object's base64 scripts are decoded when de-serialized the first time for making the configuration file. The other times the JSON is de-serialized (reading from this file), a decoded scripts pair class is used so that it doesn't attempt to decode the scripts again.
Resolves #148 
The code uses the actual scripts.json configuration file instead of hard-coded scripts I had earlier in the program to test it out.
Resolves #79 
Control Panel Shell item script worked when used through the configuration file (like it did when it was used in my little test function within the program earlier this week). With how the code is written now, you won't see the script used since I took out …

Embedded Scripting

---

WPF/SeeShells/SeeShells/ShellParser/ConfigParser.cs
WPF/SeeShells/SeeShells/ShellParser/IConfigParser.cs
WPF/SeeShells/SeeShells/ShellParser/Registry/OfflineRegistryReader.cs
WPF/SeeShells/SeeShells/ShellParser/Registry/OnlineRegistryReader.cs
WPF/SeeShells/SeeShellsTests/ShellParser/ShellBagParserTests.cs
WPF/SeeShells/SeeShellsTests/ShellParser/ShellParserMocks/MockConfigParser.cs
WPF/SeeShells/SeeShellsTests/ShellParser/ShellParserMocks/OfflineMockConfigParser.cs

- Fixes Online username error of setting last username to all values
- temporarily adds hardcoded username retrieval value which needs to be expanded upon
Resolves #164 However new issues/improvements need to be made. 
Specifically:
- Offline username retrieval is currently done through a hardcoded value which will only work on vista+ this value/potential keys that contain the username need to be added to a configuration.
- online username currently retrieve SID's because they are guaranteed and its non-trivial to resolve SID's to usernames without the SAM registry hive. Therefore live parsing should use the same username locations as offline and fallback to SID's when not available.

Adds Offline username retrieval support

---

WPF/SeeShells/SeeShells/UI/Node/NodeCollection.cs
WPF/SeeShells/SeeShells/UI/Pages/Home.xaml.cs
WPF/SeeShells/SeeShells/UI/Pages/TimelinePage.xaml.cs

The timeline is rebuilt every time a filter is applied or removed.
The rebuilt timeline only contains events that have not been filtered out and scales according to those events. 
Also added a check to the parse button that checks if a timeline has been built previously, and it it has it rebuilds it.
Resolves #194.

Filterable timeline

---

WPF/SeeShells/SeeShells/SeeShells.csproj
WPF/SeeShells/SeeShells/ShellParser/ConfigParser.cs
WPF/SeeShells/SeeShells/UI/Pages/Home.xaml.cs
WPF/SeeShells/SeeShells/resources/defaultOS.json

- Adds embedded OS Configuration file
- Adds Prompts for user confirmation on missing/invalid configs
No default config file needed for the following:
- GUID's:  already embedded with `KnownGUID` file
- Scripts: program works without scripts by default. (#140)
Resolves #137

Adds default configuration support to WPF

---

WPF/SeeShells/SeeShells/UI/Node/NodeCollection.cs
WPF/SeeShells/SeeShells/UI/Pages/Home.xaml.cs
WPF/SeeShells/SeeShellsTests/SeeShellsTests.csproj
WPF/SeeShells/SeeShellsTests/UI/Mocks/MockNodeFilter.cs
WPF/SeeShells/SeeShellsTests/UI/NodeCollectionTest.cs

- Adds unit test for new NodeCollection functionality
- improves isolation in existing NodeCollection test
Resolves #196

Clear all filters on new parsing attempt

---

WPF/SeeShells/SeeShells/IO/CsvIO.cs
WPF/SeeShells/SeeShells/SeeShells.csproj
WPF/SeeShells/SeeShells/packages.config
WPF/SeeShells/SeeShellsTests/IO/CsvIOTests.cs

Export:
Encloses every cell in double quotes in order to preserve all special characters in that cell.
If there are double quotes in a given cell, they get wrapped in double quotes.
For more info: https://hawq.apache.org/docs/userguide/2.3.0.0-incubating/datamgmt/load/g-escaping-in-csv-formatted-files.html
Import:
Uses CSVHelper (imported from NuGet) to parse a CSV file that is being imported.
TestCase:
Exports a CSV for a shellitem that contains special characters in the name field, and parses that file to check if all fields were read correctly into memory.
*Note: 
@yara-58, you should pull this branch and try exporting and then importing your ShellBags on the laptop you used when you found this bug, to further confirm that the bug is fixed.
Resolves #206

Special character support for CSV Import/Export

---

WPF/SeeShells/SeeShells/SeeShells.csproj
WPF/SeeShells/SeeShells/UI/Node/StackedNodes.cs
WPF/SeeShells/SeeShells/UI/Pages/TimelinePage.xaml.cs

Creates a new graphical object called `StackedNodes` that will be used to represent a cluster of nodes that have the same exact `EventTime`.
The `StackedNodes` object contains a list of all the events for the nodes that it combines into one and it extends Button in order to be a graphical object.
The `StackedNodes` is distinguishable from the rest of the nodes, by having a number that represents how many nodes it contains.
It does not have click functionality, as that will be added later by @bridCquinn.
Resolves #219

No More Stacked Nodes

---

WPF/SeeShells/README.md
WPF/SeeShells/SeeShells/SeeShells.csproj
WPF/SeeShells/SeeShells/UI/Pages/HelpPage.xaml
WPF/SeeShells/SeeShells/UI/Pages/HelpPage.xaml.cs
WPF/SeeShells/SeeShells/packages.config

- Adds Package and Window showing Markdown integration
- Adds basic Readme file to WPF
- Adds offline readme file skeleton
*note* This merely is a proof of concept, new issues will have to be made for proper design choice of the help window, integration with API call, etc. 
Starts on #208, potentially resolves #207

Adds Proof of Concept Markdown rendering for WPF Help

---

WPF/SeeShells/SeeShells/IO/Networking/API.cs
WPF/SeeShells/SeeShells/IO/Networking/JSON/HelpItem.cs
WPF/SeeShells/SeeShells/SeeShells.csproj
WPF/SeeShells/SeeShells/UI/Pages/HelpPage.xaml
WPF/SeeShells/SeeShells/UI/Pages/HelpPage.xaml.cs
WPF/SeeShells/SeeShellsTests/IO/Networking/APITests.cs
WPF/SeeShells/SeeShellsTests/TestResource/sampleHelp.md
WPF/SeeShells/SeeShellsTests/TestResource/sampleHelpResponse.json

- Adds help content caching into current executable directory
- Refactored API slightly to decouple writing to FS & getting API data
Current testing within the current Help API specification, the markdown seems to work when we put just plain text into the database. Depending on how the website will want to render it, we might have to switch to encoding the help content itself (e.g. base64)
Resolves #231

Adds Support for getting Help content from API

---

WPF/SeeShells/SeeShells/UI/EventFilters/EventUserFilter.cs
WPF/SeeShells/SeeShellsTests/UI/NodeFilterTests.cs

- No longer applies filter for event user when no selections have been made for users
- Updates unit test case to reflect expected behavior
Resolves #250

Fixes bug when clearing Event User filter

---

WPF/SeeShells/SeeShells/UI/EventFilters/EventParentFilter.cs
WPF/SeeShells/SeeShells/UI/Node/NodeParser.cs
WPF/SeeShells/SeeShells/UI/Pages/TimelinePage.xaml
WPF/SeeShells/SeeShells/UI/Pages/TimelinePage.xaml.cs

Adds the ability to use the filter that filters events by an even't parent.
The filter is used through a right click context menu on an event's block and gives the option to filter the timeline by this event's parent.
After the filter is applied it is indicated by stating the name of the parent that the timeline was filtered by in the Event Parent Filter filter box on the left hand side of the UI.
The filter can then be cleared by pressing the clear button.
Resolves #256

Access parent filter with right click on an even't block

---

WPF/SeeShells/SeeShells/UI/Pages/TimelinePage.xaml
WPF/SeeShells/SeeShells/UI/Pages/TimelinePage.xaml.cs

This fixes the horizontal alignment of the blocks with the nodes. 
This shows the last node on the timeline.
Resolves #242

Position blocks horizontal

---

WPF/SeeShells/SeeShells/ShellParser/Scripting/LuaShellItem.cs
WPF/SeeShells/SeeShells/ShellParser/Scripting/ScriptHandler.cs
WPF/SeeShells/SeeShells/ShellParser/ShellItems/ShellItemList.cs

Resolves #255 
Resolves #253 
These changes can be seen in ShellItemList.cs
Instead of checking for the type class first, we look for an existing script. If the script exists, we use it to parse the shell item. If successful, the shell item is returned; otherwise, the code continues and checks if a type class exists for the shell item. If type is null, the shell item goes into the unknown bucket. Code should only rearranged/reorganized here instead of modified in any way.
These changes can be seen in LuaShellItem and ScriptHandler.
The identifier was added to the LuaShellItem constructor to make it easy to identify which scripts were breaking when logging an error message.
ParseShellItems was not having its exceptions be caught, and that seemed to be causing the crashing issue. Wrapping …

Lua script modifications

---

WPF/SeeShells/SeeShells/ShellParser/Registry/OnlineRegistryReader.cs
WPF/SeeShells/SeeShells/ShellParser/Registry/RegistryHelper.cs
WPF/SeeShells/SeeShells/ShellParser/Registry/RegistryKeyWrapper.cs
WPF/SeeShells/SeeShells/ShellParser/Registry/RegistryShellItemDecorator.cs
WPF/SeeShells/SeeShellsTests/SeeShellsTests.csproj

- Refactors RegistryKeyWrapper and key retrieval to support additional properties
- Adds additional logging for registry related processes
This PR is the beginning of retrieving additional information from the windows registry surrounding the Shellbag and their data (aka Registry metadata) The following Pieces of information are now included in all shellbags when using _**Online Parsing only**_
- Last Registry Write Date (the last time the registry key was interacted with for updating a shellbag as seen from it's parent)
- Shellbag Path (The path in the registry under BagsMRU) where the shellbag is hierarchically located
- SlotModified Date (the last time the registry key in the Shellbag path was updated)
Additional PR's and work is needed to enable this same information retrieval from …

Adds additional Registry metadata from live/Online hives

---

WPF/SeeShells/SeeShells/UI/Node/Node.cs
WPF/SeeShells/SeeShells/UI/Node/StackedNodes.cs
WPF/SeeShells/SeeShells/UI/Pages/TimelinePage.xaml
WPF/SeeShells/SeeShells/UI/Pages/TimelinePage.xaml.cs
WPF/SeeShells/SeeShells/UI/Windows/EventInformationWindow.xaml

I had an idea for resolving #244 but it failed; however, I made this modification while working through it.
Instead of making a bunch of hidden boxes, we can just make one per stack and make it the height of the needed boxes combined. This helps with the massive memory issue.
To avoid the awkward stacking issue when two nodes are close to each other, we can hide the stacks that conflict with the ones we want to open most recently (see the pictures). I think this works better for clicking around and viewing a bunch of events. This also solves the "jittering" problem Aleks and Bridget were talking about (I only understood what that issue was when working on this today).
With this PR, the events should always be visible when you click on them.
Click on the 6 node:
Clicking on the 3 node:
As …

Possibe alignment modification

---

WPF/SeeShells/SeeShells/ShellParser/Registry/RegistryKeyWrapper.cs

Partially Addressed #259 
It was discovered that DateTimes retrieved from the registry (that are not in shellbags) are in the Timezone of the machine instead of UTC like the shellbag data.
This is to prevent double conversions that can occur from future work in #259 
This PR makes it uniform UTC when retrieving any DateTime from an IShellItem

Converts Registry obtained DateTimes into UTC

---

WPF/SeeShells/SeeShells/UI/Pages/TimelinePage.xaml.cs

- Fixed issue where HTML output wasn't being filtered
- Fixed bug where WPF would crash if no selection was made during saving
Resolves #284 
Resolves #280

Fixes HTML filtering and crashing on no save selection

---

WPF/SeeShells/SeeShells/ShellParser/Registry/OnlineRegistryReader.cs
WPF/SeeShells/SeeShells/ShellParser/Registry/RegistryKeyWrapper.cs
WPF/SeeShells/SeeShells/ShellParser/Registry/RegistryShellItemDecorator.cs
WPF/SeeShells/SeeShells/ShellParser/ShellBagParser.cs

- Slight refactoring to OnlineRegistryReader to shift responsibility of data
- Refactored ShellBagParser  to have RegistryKey to Shellbag relations known
- Refactored RegistryShellItemDecorator to make Parent-Aware ShellItems
- Added Registry SID (User account) Data to extracted registry info
As of writing, _**Online Parsing**_ correctly supplies Absolute Path values for output, _**Offline Parsing**_ does not. ( for the reasons mentioned in #271)

Adds Absolute Path data to all ShellItems

---

WPF/SeeShells/SeeShells/UI/Pages/TimelinePage.xaml.cs

If the user tries to export CSV output to an already existing CSV file that is currently opened by another process for editing, the program will notify the user with a message box, log the exception and proceed without exporting the CSV file.
Resolves #279

Prevents program crash when trying to write to a CSV file locked for editing

---

WPF/SeeShells/SeeShells/IO/HtmlIO.cs
WPF/SeeShells/SeeShells/ShellParser/Registry/RegistryShellItemDecorator.cs
WPF/SeeShells/SeeShells/UI/Event.cs
WPF/SeeShells/SeeShells/UI/EventParser.cs
WPF/SeeShells/SeeShells/UI/IEvent.cs
WPF/SeeShells/SeeShells/UI/Node/InfoBlock.cs
WPF/SeeShells/SeeShellsTests/UI/Mocks/MockEvent.cs

My solution to this bug was to convert all the datetimes from UTC to the Users local timezone on their system before they are added as part of an event. This was made possible by Klayton making all the registry DateTimes UTC, whereas before they were based on the user's computer while shellbags were based on Utc. I also added the Local Time Zone on the computer to the HTML output. I tested it using multiple timezones on my computer and the EventTimes change to that of the current timezone. 
this closes issue #259

Timezone addition

---

WPF/SeeShells/SeeShells/App.xaml
WPF/SeeShells/SeeShells/UI/Pages/TimelinePage.xaml
WPF/SeeShells/SeeShells/UI/Pages/TimelinePage.xaml.cs

Resolves #295 . The Timeline Panel was moving around the screen when it was being resized. That no longer happens. The background of the Timeline Grid has been changed to match the background of the application. In place of an empty screen when no nodes are showing, the words "No Events to Show" appear on the screen. I bug fix of changing an wrap to a dock panel happened.

Remaster gui

---

WPF/SeeShells/SeeShells/UI/Pages/Home.xaml.cs

- No longer displays invalid configuration warnings if the advanced section is not visible
Resolves #257

Adds Advanced Configuration conditional to invalid config warnings

---

WPF/SeeShells/SeeShells/UI/Pages/TimelinePage.xaml.cs

- Fixes bug where the End Date option on the UI was not inclusive of it's day as per the documentation for the EndDateFilter
Steps to reproduce error (before this PR)
1. Use Seeshells to view a timeline with at least one date
2. Set the start date and end date in the Event Date Filter to the same date
3. Observe no timeline is displayed.

Fix End Date Filter UI not being inclusive of the date

---

WPF/SeeShells/SeeShells/ShellParser/Registry/OfflineRegistryReader.cs
WPF/SeeShells/SeeShells/ShellParser/Registry/RegistryKeyWrapper.cs

The new modifications to the offline parser make it build registry key wrappers while parsing and enable it to gather time based registry metadata for shellitems such as:
- SlotModifiedDate
- LastRegistryWriteDate
- ShellbagPath
- Parent
Resolves: #281

Modifies the offline parser to retrieve additional time based registry metadata for shellitems

---

WPF/SeeShells/SeeShells/SeeShells.csproj
WPF/SeeShells/SeeShells/UI/Node/NodeNavigation.cs
WPF/SeeShells/SeeShells/UI/Pages/TimelinePage.xaml
WPF/SeeShells/SeeShells/UI/Pages/TimelinePage.xaml.cs
WPF/SeeShells/SeeShells/UI/Templates/NodeStyle.xaml

Adds two UI buttons that allow a user to navigate forwards and backwards trough the nodes, one node at a time. (I did not use the arrow keys binding, since an initial click to focus is required and also the arrows are use by the timeline scrollbar by default.)
Navigation starts from the second node when the  forwards button is pressed. (The navigation is not circular. When the end is reached, pressing the button does noting. Same applies in the opposite direction)
When a node is brought into view, it also changes color to signify that it has been navigated to.
When a user left clicks on a node, the navigation makes that node the node to start navigating from. Otherwise navigation starts from the second node or wherever it was left off.
Tested and works when the timeline is rebuilt. …

Adds single node navigation capability

---

WPF/SeeShells/SeeShells/UI/Pages/Home.xaml.cs

resolves issue #319
clears the nodelist when re-parsing which eliminates adding new information to a previous parse which in turn eliminates the stacking issue that was occurring.

clears timeline when re-parsing

---

WPF/SeeShells/SeeShells/UI/Pages/TimelinePage.xaml.cs

Resolves #293 
When calculating the max nodes, we would count up with a local variable when the event time was the same as a previous node and do a comparison to replace maxStackedNodes when the event time was different from the previous node. I realized we would never make the comparison for any last group of nodes, thus possibly miscalculating the maxStackedNodes. It seemed likely that the case study VM would have this (probably) rare situation where there was a bunch of nodes at the end since it's not a normally used machine with a bunch of normal shellbag events.
Adding this final comparison check between maxStackedNodes and currentMaxStackedNodes seems to have fixed the issue. @klaki892 tested it on the Corporate Fraud case study VM. The program was run 5 times, resetting the VM each …

Fixed negative height issue

---

WPF/SeeShells/SeeShells/ShellParser/Registry/OnlineRegistryReader.cs

The `OnlineRegistryReader` tries to resolve the actual usernames of users first and uses SIDs if resolving failed.
Resolves #192

Online parsing resolves actual user name before showing SID.

---

WPF/SeeShells/SeeShells/IO/CsvIO.cs
WPF/SeeShells/SeeShells/IO/CsvParsedShellItem.cs
WPF/SeeShells/SeeShells/SeeShells.csproj
WPF/SeeShells/SeeShells/ShellParser/Registry/OfflineRegistryReader.cs
WPF/SeeShells/SeeShells/ShellParser/Registry/OnlineRegistryReader.cs
WPF/SeeShells/SeeShells/ShellParser/ShellItems/IShellItem.cs
WPF/SeeShells/SeeShells/ShellParser/ShellItems/ShellItem.cs
WPF/SeeShells/SeeShells/ShellParser/ShellItems/ShellItem0x00.cs
WPF/SeeShells/SeeShells/UI/LogAggregator.cs
WPF/SeeShells/SeeShells/UI/Pages/Home.xaml.cs
WPF/SeeShells/SeeShells/UI/Templates/Switch.xaml.cs

- Adds Log message aggregator to display message boxes of information about a parsing operation
- Adds Error handling to support invalid files being passed to CSV parser and Offline Hive parser
- Fixes CSV file appending all changes to existing files, causing subsequent reading errors due to multiple header rows
- Fixes CSV import failing to a read a file if another program has the same file open
- Added check for required Event fields on CSV Import, shows error message detailing if missing basic required information
- Adds error messages for individual line items in a CSV Import operation
- fixes case where offline and online usernames not being found would cause program to crash
- Fixes Shellbag0x01 and all unknown shellbags not having a TypeName field, a required piece of information …

Fix IO Error handling for hives and CSV files and various related bugs

---

WPF/SeeShells/SeeShells/UI/Pages/Home.xaml

With the addition of the new multi user checkbox, the alignment got pushed somehow. It was a quick fix by just adding a horizontal alignment.
This is what it used to look like, it is now back to normal.

Fixed Alignment
